"""AWS Bedrock pricing for Anthropic Claude models.

Anthropic-on-Bedrock pricing, shared by lmux-aws-bedrock (Converse) and the
native lmux-anthropic Bedrock provider so Claude is priced identically by both.
Only the Anthropic subset lives here; other Bedrock vendors are priced in
lmux_aws_bedrock.cost.

Auto-generated by scripts/update_bedrock_pricing.py -- do not edit manually.

Pricing source: https://aws.amazon.com/bedrock/pricing/
"""

from datetime import date

from lmux.cost import ModelPricing, PricingSchedule, PricingTier, calculate_cost, per_million_tokens
from lmux.types import Cost, Usage

ANTHROPIC_PRICING: dict[str, ModelPricing] = {
    "anthropic.claude-3-5-haiku-20241022-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=per_million_tokens(4.0),
                cache_read_cost_per_token=per_million_tokens(0.08),
                cache_creation_cost_per_token=per_million_tokens(1.0),
            ),
        ],
    ),
    "anthropic.claude-3-5-sonnet-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "anthropic.claude-3-5-sonnet-v2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "anthropic.claude-3-7-sonnet-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "anthropic.claude-3-haiku-20240307-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.25),
                output_cost_per_token=per_million_tokens(1.25),
            ),
        ],
    ),
    "anthropic.claude-3-opus-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(15.0),
                output_cost_per_token=per_million_tokens(75.0),
            ),
        ],
    ),
    "anthropic.claude-3-sonnet-20240229-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "anthropic.claude-fable-5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(11.0),
                output_cost_per_token=per_million_tokens(55.0),
                cache_read_cost_per_token=per_million_tokens(1.1),
                cache_creation_cost_per_token=per_million_tokens(13.75),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(22.0)},
            ),
        ],
    ),
    "anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.1),
                output_cost_per_token=per_million_tokens(5.5),
                cache_read_cost_per_token=per_million_tokens(0.11),
                cache_creation_cost_per_token=per_million_tokens(1.375),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(2.2)},
            ),
        ],
    ),
    "anthropic.claude-instant-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=per_million_tokens(2.4),
            ),
        ],
    ),
    "anthropic.claude-mythos-5-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(11.0),
                output_cost_per_token=per_million_tokens(55.0),
                cache_read_cost_per_token=per_million_tokens(1.1),
                cache_creation_cost_per_token=per_million_tokens(13.75),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(22.0)},
            ),
        ],
    ),
    "anthropic.claude-opus-4-1-20250805-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(15.0),
                output_cost_per_token=per_million_tokens(75.0),
                cache_read_cost_per_token=per_million_tokens(1.5),
                cache_creation_cost_per_token=per_million_tokens(18.75),
            ),
        ],
    ),
    "anthropic.claude-opus-4-5-20251101-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "anthropic.claude-opus-4-6-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "anthropic.claude-opus-4-8": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "anthropic.claude-opus-4-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(15.0),
                output_cost_per_token=per_million_tokens(75.0),
                cache_read_cost_per_token=per_million_tokens(1.5),
                cache_creation_cost_per_token=per_million_tokens(18.75),
            ),
        ],
    ),
    "anthropic.claude-sonnet-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
            ),
        ],
    ),
    "anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
            ),
        ],
    ),
    "anthropic.claude-sonnet-5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.2),
                output_cost_per_token=per_million_tokens(11.0),
                cache_read_cost_per_token=per_million_tokens(0.22),
                cache_creation_cost_per_token=per_million_tokens(2.75),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(4.4)},
            ),
        ],
        schedules=[
            PricingSchedule(
                valid_from=date(2026, 9, 1),
                tiers=[
                    PricingTier(
                        input_cost_per_token=per_million_tokens(3.3),
                        output_cost_per_token=per_million_tokens(16.5),
                        cache_read_cost_per_token=per_million_tokens(0.33),
                        cache_creation_cost_per_token=per_million_tokens(4.125),
                        cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
                    ),
                ],
            ),
        ],
    ),
    "anthropic.claude-v2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(8.0),
                output_cost_per_token=per_million_tokens(24.0),
            ),
        ],
    ),
    "apac.anthropic.claude-3-haiku-20240307-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.25),
                output_cost_per_token=per_million_tokens(1.25),
            ),
        ],
    ),
    "apac.anthropic.claude-3-sonnet-20240229-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "apac.anthropic.claude-sonnet-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "au.anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.1),
                output_cost_per_token=per_million_tokens(5.5),
                cache_read_cost_per_token=per_million_tokens(0.11),
                cache_creation_cost_per_token=per_million_tokens(1.375),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(2.2)},
            ),
        ],
    ),
    "au.anthropic.claude-opus-4-6-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "au.anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "au.anthropic.claude-opus-4-8": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "au.anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
            ),
        ],
    ),
    "au.anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
            ),
        ],
    ),
    "eu.anthropic.claude-3-haiku-20240307-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.25),
                output_cost_per_token=per_million_tokens(1.25),
            ),
        ],
    ),
    "eu.anthropic.claude-3-sonnet-20240229-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "eu.anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.1),
                output_cost_per_token=per_million_tokens(5.5),
                cache_read_cost_per_token=per_million_tokens(0.11),
                cache_creation_cost_per_token=per_million_tokens(1.375),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(2.2)},
            ),
        ],
    ),
    "eu.anthropic.claude-opus-4-5-20251101-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "eu.anthropic.claude-opus-4-6-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "eu.anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "eu.anthropic.claude-opus-4-8": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "eu.anthropic.claude-sonnet-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "eu.anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
            ),
        ],
    ),
    "eu.anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
            ),
        ],
    ),
    "eu.anthropic.claude-sonnet-5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.2),
                output_cost_per_token=per_million_tokens(11.0),
                cache_read_cost_per_token=per_million_tokens(0.22),
                cache_creation_cost_per_token=per_million_tokens(2.75),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(4.4)},
            ),
        ],
        schedules=[
            PricingSchedule(
                valid_from=date(2026, 9, 1),
                tiers=[
                    PricingTier(
                        input_cost_per_token=per_million_tokens(3.3),
                        output_cost_per_token=per_million_tokens(16.5),
                        cache_read_cost_per_token=per_million_tokens(0.33),
                        cache_creation_cost_per_token=per_million_tokens(4.125),
                        cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
                    ),
                ],
            ),
        ],
    ),
    "global.anthropic.claude-fable-5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(10.0),
                output_cost_per_token=per_million_tokens(50.0),
                cache_read_cost_per_token=per_million_tokens(1.0),
                cache_creation_cost_per_token=per_million_tokens(12.5),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(20.0)},
            ),
        ],
    ),
    "global.anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.0),
                output_cost_per_token=per_million_tokens(5.0),
                cache_read_cost_per_token=per_million_tokens(0.1),
                cache_creation_cost_per_token=per_million_tokens(1.25),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(2.0)},
            ),
        ],
    ),
    "global.anthropic.claude-opus-4-5-20251101-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.0),
                output_cost_per_token=per_million_tokens(25.0),
                cache_read_cost_per_token=per_million_tokens(0.5),
                cache_creation_cost_per_token=per_million_tokens(6.25),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(10.0)},
            ),
        ],
    ),
    "global.anthropic.claude-opus-4-6-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.0),
                output_cost_per_token=per_million_tokens(25.0),
                cache_read_cost_per_token=per_million_tokens(0.5),
                cache_creation_cost_per_token=per_million_tokens(6.25),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(10.0)},
            ),
        ],
    ),
    "global.anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.0),
                output_cost_per_token=per_million_tokens(25.0),
                cache_read_cost_per_token=per_million_tokens(0.5),
                cache_creation_cost_per_token=per_million_tokens(6.25),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(10.0)},
            ),
        ],
    ),
    "global.anthropic.claude-opus-4-8": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.0),
                output_cost_per_token=per_million_tokens(25.0),
                cache_read_cost_per_token=per_million_tokens(0.5),
                cache_creation_cost_per_token=per_million_tokens(6.25),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(10.0)},
            ),
        ],
    ),
    "global.anthropic.claude-sonnet-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "global.anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.0)},
            ),
        ],
    ),
    "global.anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.0)},
            ),
        ],
    ),
    "global.anthropic.claude-sonnet-5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.0),
                output_cost_per_token=per_million_tokens(10.0),
                cache_read_cost_per_token=per_million_tokens(0.2),
                cache_creation_cost_per_token=per_million_tokens(2.5),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(4.0)},
            ),
        ],
        schedules=[
            PricingSchedule(
                valid_from=date(2026, 9, 1),
                tiers=[
                    PricingTier(
                        input_cost_per_token=per_million_tokens(3.0),
                        output_cost_per_token=per_million_tokens(15.0),
                        cache_read_cost_per_token=per_million_tokens(0.3),
                        cache_creation_cost_per_token=per_million_tokens(3.75),
                        cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.0)},
                    ),
                ],
            ),
        ],
    ),
    "jp.anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.1),
                output_cost_per_token=per_million_tokens(5.5),
                cache_read_cost_per_token=per_million_tokens(0.11),
                cache_creation_cost_per_token=per_million_tokens(1.375),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(2.2)},
            ),
        ],
    ),
    "jp.anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "jp.anthropic.claude-opus-4-8": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "jp.anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
            ),
        ],
    ),
    "jp.anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
            ),
        ],
    ),
    "us.anthropic.claude-3-haiku-20240307-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.25),
                output_cost_per_token=per_million_tokens(1.25),
            ),
        ],
    ),
    "us.anthropic.claude-3-sonnet-20240229-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "us.anthropic.claude-fable-5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(11.0),
                output_cost_per_token=per_million_tokens(55.0),
                cache_read_cost_per_token=per_million_tokens(1.1),
                cache_creation_cost_per_token=per_million_tokens(13.75),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(22.0)},
            ),
        ],
    ),
    "us.anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.1),
                output_cost_per_token=per_million_tokens(5.5),
                cache_read_cost_per_token=per_million_tokens(0.11),
                cache_creation_cost_per_token=per_million_tokens(1.375),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(2.2)},
            ),
        ],
    ),
    "us.anthropic.claude-opus-4-1-20250805-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(15.0),
                output_cost_per_token=per_million_tokens(75.0),
                cache_read_cost_per_token=per_million_tokens(1.5),
                cache_creation_cost_per_token=per_million_tokens(18.75),
            ),
        ],
    ),
    "us.anthropic.claude-opus-4-5-20251101-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "us.anthropic.claude-opus-4-6-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "us.anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "us.anthropic.claude-opus-4-8": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(11.0)},
            ),
        ],
    ),
    "us.anthropic.claude-sonnet-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "us.anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
            ),
        ],
    ),
    "us.anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
            ),
        ],
    ),
    "us.anthropic.claude-sonnet-5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.2),
                output_cost_per_token=per_million_tokens(11.0),
                cache_read_cost_per_token=per_million_tokens(0.22),
                cache_creation_cost_per_token=per_million_tokens(2.75),
                cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(4.4)},
            ),
        ],
        schedules=[
            PricingSchedule(
                valid_from=date(2026, 9, 1),
                tiers=[
                    PricingTier(
                        input_cost_per_token=per_million_tokens(3.3),
                        output_cost_per_token=per_million_tokens(16.5),
                        cache_read_cost_per_token=per_million_tokens(0.33),
                        cache_creation_cost_per_token=per_million_tokens(4.125),
                        cache_creation_cost_per_token_by_ttl={"1h": per_million_tokens(6.6)},
                    ),
                ],
            ),
        ],
    ),
}

_PRICING_BY_PREFIX = sorted(ANTHROPIC_PRICING.items(), key=lambda item: len(item[0]), reverse=True)


# Cross-region inference profile prefixes. A profile call (e.g. "us.anthropic...")
# with no dedicated regional entry falls back to the base model's pricing.
_INFERENCE_PROFILE_PREFIXES = ("global.", "us.", "eu.", "apac.", "au.", "jp.", "ca.")


def _strip_profile_prefix(model: str) -> str:
    for prefix in _INFERENCE_PROFILE_PREFIXES:
        if model.startswith(prefix):
            return model[len(prefix) :]
    return model


def _lookup_pricing(model: str) -> ModelPricing | None:
    pricing = ANTHROPIC_PRICING.get(model)
    if pricing is not None:
        return pricing
    for prefix, p in _PRICING_BY_PREFIX:
        if model.startswith(prefix):
            return p
    bare = _strip_profile_prefix(model)
    if bare != model:
        return _lookup_pricing(bare)
    return None


def calculate_bedrock_anthropic_cost(model: str, usage: Usage, *, as_of: date | None = None) -> Cost | None:
    """Calculate cost for a native Anthropic-on-Bedrock call. None if pricing is unknown.

    Handles both bare model IDs and cross-region inference-profile IDs
    (e.g. ``us.anthropic.claude-opus-4-8``). ``as_of`` selects dated pricing for
    models with scheduled rate changes (e.g. Claude Sonnet 5's introductory
    period); it defaults to the latest schedule. See ``lmux.cost.calculate_cost``.
    """
    pricing = _lookup_pricing(model)
    if pricing is None:
        return None
    return calculate_cost(usage, pricing, as_of)
