"""AWS Bedrock pricing data and cost calculation.

Prices are for the us-east-1 region (on-demand). Use register_pricing()
on BedrockProvider for overrides or other regions.

Auto-generated by scripts/update_bedrock_pricing.py — manual edits will be overwritten.
"""

from lmux.cost import ModelPricing, PricingTier, calculate_cost, per_million_tokens
from lmux.types import Cost, Usage

_PRICING: dict[str, ModelPricing] = {
    # ── Amazon Nova ────────────────────────────────────────────
    "amazon.nova-2-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(0.125),
                cache_read_cost_per_token=per_million_tokens(0.075),
            )
        ]
    ),
    "amazon.nova-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.03),
                output_cost_per_token=per_million_tokens(0.12),
                cache_read_cost_per_token=per_million_tokens(0.015),
            )
        ]
    ),
    "amazon.nova-micro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.035),
                output_cost_per_token=per_million_tokens(0.07),
                cache_read_cost_per_token=per_million_tokens(0.0087),
            )
        ]
    ),
    "amazon.nova-premier-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.25),
                output_cost_per_token=per_million_tokens(12.5),
                cache_read_cost_per_token=per_million_tokens(0.625),
            )
        ]
    ),
    "amazon.nova-pro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=per_million_tokens(1.6),
                cache_read_cost_per_token=per_million_tokens(0.2),
            )
        ]
    ),
    # ── Amazon Titan ───────────────────────────────────────────
    "amazon.titan-embed-image-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=0.0,  # TODO: missing from API
            )
        ]
    ),
    "amazon.titan-embed-text-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=0.0,  # TODO: missing from API
            )
        ]
    ),
    "amazon.titan-embed-text-v2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.01),
                output_cost_per_token=0.0,  # TODO: missing from API
            )
        ]
    ),
    # ── Anthropic Claude (via Bedrock) ─────────────────────────
    "anthropic.claude-3-haiku-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.25),
                output_cost_per_token=0.0,  # TODO: missing from API
            )
        ]
    ),
    "anthropic.claude-3-sonnet-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=0.0,  # TODO: missing from API
            )
        ]
    ),
    # ── DeepSeek (via Bedrock) ─────────────────────────────────
    "deepseek.r1-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.35),
                output_cost_per_token=per_million_tokens(5.4),
            )
        ]
    ),
    "deepseek.v3.2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.62),
                output_cost_per_token=per_million_tokens(1.85),
            )
        ]
    ),
    # ── Meta Llama (via Bedrock) ───────────────────────────────
    "meta.llama3-1-70b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.72),
                output_cost_per_token=per_million_tokens(0.72),
            )
        ]
    ),
    "meta.llama3-1-8b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.11),
                output_cost_per_token=per_million_tokens(0.22),
            )
        ]
    ),
    "meta.llama3-2-11b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.16),
                output_cost_per_token=per_million_tokens(0.16),
            )
        ]
    ),
    "meta.llama3-2-1b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=per_million_tokens(0.1),
            )
        ]
    ),
    "meta.llama3-2-3b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.15),
            )
        ]
    ),
    "meta.llama3-2-90b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.72),
                output_cost_per_token=per_million_tokens(0.72),
            )
        ]
    ),
    "meta.llama3-3-70b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.72),
                output_cost_per_token=per_million_tokens(0.36),
            )
        ]
    ),
    "meta.llama3-70b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.65),
                output_cost_per_token=per_million_tokens(3.5),
            )
        ]
    ),
    "meta.llama3-8b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(0.6),
            )
        ]
    ),
    "meta.llama4-maverick-17b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.24),
                output_cost_per_token=per_million_tokens(0.97),
            )
        ]
    ),
    "meta.llama4-scout-17b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.085),
                output_cost_per_token=per_million_tokens(0.33),
            )
        ]
    ),
    # ── Mistral (via Bedrock) ──────────────────────────────────
    "mistral.devstral-2-123b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.4),
                output_cost_per_token=per_million_tokens(2.0),
            )
        ]
    ),
    "mistral.magistral-small-2509": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.25),
                output_cost_per_token=per_million_tokens(1.5),
            )
        ]
    ),
    "mistral.ministral-3-14b-instruct": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.2),
                output_cost_per_token=per_million_tokens(0.2),
            )
        ]
    ),
    "mistral.ministral-3-3b-instruct": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=per_million_tokens(0.1),
            )
        ]
    ),
    "mistral.ministral-3-8b-instruct": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.15),
            )
        ]
    ),
    "mistral.mistral-7b-instruct-v0:2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.2),
            )
        ]
    ),
    "mistral.mistral-large-2402-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(4.0),
                output_cost_per_token=per_million_tokens(12.0),
            )
        ]
    ),
    "mistral.mistral-large-3-675b-instruct": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.5),
                output_cost_per_token=per_million_tokens(0.75),
            )
        ]
    ),
    "mistral.mistral-small-2402-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.0),
                output_cost_per_token=per_million_tokens(1.5),
            )
        ]
    ),
    "mistral.mixtral-8x7b-instruct-v0:1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.45),
                output_cost_per_token=per_million_tokens(0.7),
            )
        ]
    ),
    "mistral.pixtral-large-2502-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.0),
                output_cost_per_token=per_million_tokens(6.0),
            )
        ]
    ),
    "mistral.voxtral-mini-3b-2507": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.04),
                output_cost_per_token=per_million_tokens(0.04),
            )
        ]
    ),
    "mistral.voxtral-small-24b-2507": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.05),
                output_cost_per_token=per_million_tokens(0.3),
            )
        ]
    ),
    # ── Other ──────────────────────────────────────────────────
    "google.gemma-3-12b-it": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.09),
                output_cost_per_token=per_million_tokens(0.29),
            )
        ]
    ),
    "google.gemma-3-27b-it": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.23),
                output_cost_per_token=per_million_tokens(0.38),
            )
        ]
    ),
    "google.gemma-3-4b-it": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.04),
                output_cost_per_token=per_million_tokens(0.08),
            )
        ]
    ),
    "minimax.minimax-m2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(1.2),
            )
        ]
    ),
    "minimax.minimax-m2.1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(1.2),
            )
        ]
    ),
    "moonshot.kimi-k2-thinking": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.6),
                output_cost_per_token=per_million_tokens(1.25),
            )
        ]
    ),
    "moonshotai.kimi-k2.5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.6),
                output_cost_per_token=per_million_tokens(3.0),
            )
        ]
    ),
    "nvidia.nemotron-nano-12b-v2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.2),
                output_cost_per_token=per_million_tokens(0.3),
            )
        ]
    ),
    "nvidia.nemotron-nano-3-30b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.06),
                output_cost_per_token=per_million_tokens(0.24),
            )
        ]
    ),
    "nvidia.nemotron-nano-9b-v2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.06),
                output_cost_per_token=per_million_tokens(0.23),
            )
        ]
    ),
    "openai.gpt-oss-120b-1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.6),
            )
        ]
    ),
    "openai.gpt-oss-20b-1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.07),
                output_cost_per_token=per_million_tokens(0.3),
            )
        ]
    ),
    "openai.gpt-oss-safeguard-120b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.6),
            )
        ]
    ),
    "openai.gpt-oss-safeguard-20b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.03),
                output_cost_per_token=per_million_tokens(0.1),
            )
        ]
    ),
    "qwen.qwen3-32b-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.075),
                output_cost_per_token=per_million_tokens(0.6),
            )
        ]
    ),
    "qwen.qwen3-coder-30b-a3b-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.075),
                output_cost_per_token=per_million_tokens(0.6),
            )
        ]
    ),
    "qwen.qwen3-coder-next": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.5),
                output_cost_per_token=per_million_tokens(1.2),
            )
        ]
    ),
    "qwen.qwen3-next-80b-a3b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.14),
                output_cost_per_token=per_million_tokens(1.2),
            )
        ]
    ),
    "qwen.qwen3-vl-235b-a22b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.53),
                output_cost_per_token=per_million_tokens(1.33),
            )
        ]
    ),
    "zai.glm-4.7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.6),
                output_cost_per_token=per_million_tokens(2.2),
            )
        ]
    ),
    "zai.glm-4.7-flash": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.07),
                output_cost_per_token=per_million_tokens(0.4),
            )
        ]
    ),
}

# Pre-sorted by key length descending for longest-prefix matching
_PRICING_BY_PREFIX = sorted(_PRICING.items(), key=lambda item: len(item[0]), reverse=True)


def calculate_bedrock_cost(model: str, usage: Usage) -> Cost | None:
    """Calculate cost for a Bedrock API call. Returns None if model pricing is unknown."""
    pricing = _PRICING.get(model)
    if pricing is None:
        for prefix, p in _PRICING_BY_PREFIX:
            if model.startswith(prefix):
                pricing = p
                break
    if pricing is None:
        return None
    return calculate_cost(usage, pricing)
