"""AWS Bedrock pricing data and cost calculation.

Prices are for the us-east-1 region (on-demand, cross-region global inference).
Use register_pricing() on BedrockProvider for overrides or other regions.

Auto-generated by scripts/update_bedrock_pricing.py -- do not edit manually.

Pricing source: https://aws.amazon.com/bedrock/pricing/
"""

from lmux.cost import ModelPricing, PricingTier, calculate_cost, per_million_tokens
from lmux.types import Cost, Usage

_PRICING: dict[str, ModelPricing] = {
    # -- Amazon Nova / Titan -------------------------------------
    "amazon.nova-2-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.33),
                output_cost_per_token=per_million_tokens(2.75),
                cache_read_cost_per_token=per_million_tokens(0.0825),
            ),
        ],
    ),
    "amazon.nova-2-omni-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(2.8),
            ),
        ],
    ),
    "amazon.nova-2-pro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.375),
                output_cost_per_token=per_million_tokens(11.0),
            ),
        ],
    ),
    "amazon.nova-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.06),
                output_cost_per_token=per_million_tokens(0.24),
                cache_read_cost_per_token=per_million_tokens(0.015),
            ),
        ],
    ),
    "amazon.nova-micro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.035),
                output_cost_per_token=per_million_tokens(0.14),
                cache_read_cost_per_token=per_million_tokens(0.00875),
            ),
        ],
    ),
    "amazon.nova-premier-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.5),
                output_cost_per_token=per_million_tokens(12.5),
                cache_read_cost_per_token=per_million_tokens(0.625),
            ),
        ],
    ),
    "amazon.nova-pro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=per_million_tokens(3.2),
                cache_read_cost_per_token=per_million_tokens(0.2),
            ),
        ],
    ),
    "amazon.titan-embed-image-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=0.0,
            ),
        ],
    ),
    "amazon.titan-embed-text-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=0.0,
            ),
        ],
    ),
    "amazon.titan-embed-text-v2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.02),
                output_cost_per_token=0.0,
            ),
        ],
    ),
    "amazon.titan-text-express-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.2),
                output_cost_per_token=per_million_tokens(0.6),
            ),
        ],
    ),
    "amazon.titan-text-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.2),
            ),
        ],
    ),
    "amazon.titan-text-premier-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.5),
                output_cost_per_token=per_million_tokens(1.5),
            ),
        ],
    ),
    "apac.amazon.nova-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.06),
                output_cost_per_token=per_million_tokens(0.24),
                cache_read_cost_per_token=per_million_tokens(0.015),
            ),
        ],
    ),
    "apac.amazon.nova-micro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.035),
                output_cost_per_token=per_million_tokens(0.14),
                cache_read_cost_per_token=per_million_tokens(0.00875),
            ),
        ],
    ),
    "apac.amazon.nova-pro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=per_million_tokens(3.2),
                cache_read_cost_per_token=per_million_tokens(0.2),
            ),
        ],
    ),
    "ca.amazon.nova-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.06),
                output_cost_per_token=per_million_tokens(0.24),
                cache_read_cost_per_token=per_million_tokens(0.015),
            ),
        ],
    ),
    "eu.amazon.nova-2-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.33),
                output_cost_per_token=per_million_tokens(2.75),
                cache_read_cost_per_token=per_million_tokens(0.0825),
            ),
        ],
    ),
    "eu.amazon.nova-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.06),
                output_cost_per_token=per_million_tokens(0.24),
                cache_read_cost_per_token=per_million_tokens(0.015),
            ),
        ],
    ),
    "eu.amazon.nova-micro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.035),
                output_cost_per_token=per_million_tokens(0.14),
                cache_read_cost_per_token=per_million_tokens(0.00875),
            ),
        ],
    ),
    "eu.amazon.nova-pro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=per_million_tokens(3.2),
                cache_read_cost_per_token=per_million_tokens(0.2),
            ),
        ],
    ),
    "global.amazon.nova-2-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(2.5),
                cache_read_cost_per_token=per_million_tokens(0.075),
            ),
        ],
    ),
    "jp.amazon.nova-2-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.33),
                output_cost_per_token=per_million_tokens(2.75),
                cache_read_cost_per_token=per_million_tokens(0.0825),
            ),
        ],
    ),
    "us.amazon.nova-2-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.33),
                output_cost_per_token=per_million_tokens(2.75),
                cache_read_cost_per_token=per_million_tokens(0.0825),
            ),
        ],
    ),
    "us.amazon.nova-lite-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.06),
                output_cost_per_token=per_million_tokens(0.24),
                cache_read_cost_per_token=per_million_tokens(0.015),
            ),
        ],
    ),
    "us.amazon.nova-micro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.035),
                output_cost_per_token=per_million_tokens(0.14),
                cache_read_cost_per_token=per_million_tokens(0.00875),
            ),
        ],
    ),
    "us.amazon.nova-premier-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.5),
                output_cost_per_token=per_million_tokens(12.5),
                cache_read_cost_per_token=per_million_tokens(0.625),
            ),
        ],
    ),
    "us.amazon.nova-pro-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=per_million_tokens(3.2),
                cache_read_cost_per_token=per_million_tokens(0.2),
            ),
        ],
    ),
    # -- AI21 Labs -----------------------------------------------
    "ai21.j2-mid-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(12.5),
                output_cost_per_token=per_million_tokens(12.5),
            ),
        ],
    ),
    "ai21.j2-ultra-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(18.8),
                output_cost_per_token=per_million_tokens(18.8),
            ),
        ],
    ),
    "ai21.jamba-1-5-large-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.0),
                output_cost_per_token=per_million_tokens(8.0),
            ),
        ],
    ),
    "ai21.jamba-1-5-mini-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.2),
                output_cost_per_token=per_million_tokens(0.4),
            ),
        ],
    ),
    "ai21.jamba-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.5),
                output_cost_per_token=per_million_tokens(0.7),
            ),
        ],
    ),
    # -- Anthropic Claude (via Bedrock) --------------------------
    "anthropic.claude-3-5-haiku-20241022-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=per_million_tokens(4.0),
                cache_read_cost_per_token=per_million_tokens(0.08),
                cache_creation_cost_per_token=per_million_tokens(1.0),
            ),
        ],
    ),
    "anthropic.claude-3-5-sonnet-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "anthropic.claude-3-5-sonnet-v2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "anthropic.claude-3-7-sonnet-20250219-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "anthropic.claude-3-haiku-20240307-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.25),
                output_cost_per_token=per_million_tokens(1.25),
            ),
        ],
    ),
    "anthropic.claude-3-opus-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(15.0),
                output_cost_per_token=per_million_tokens(75.0),
            ),
        ],
    ),
    "anthropic.claude-3-sonnet-20240229-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.1),
                output_cost_per_token=per_million_tokens(5.5),
                cache_read_cost_per_token=per_million_tokens(0.11),
                cache_creation_cost_per_token=per_million_tokens(1.375),
            ),
        ],
    ),
    "anthropic.claude-instant-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=per_million_tokens(2.4),
            ),
        ],
    ),
    "anthropic.claude-opus-4-1-20250805-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(15.0),
                output_cost_per_token=per_million_tokens(75.0),
                cache_read_cost_per_token=per_million_tokens(1.5),
                cache_creation_cost_per_token=per_million_tokens(18.75),
            ),
        ],
    ),
    "anthropic.claude-opus-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(15.0),
                output_cost_per_token=per_million_tokens(75.0),
                cache_read_cost_per_token=per_million_tokens(1.5),
                cache_creation_cost_per_token=per_million_tokens(18.75),
            ),
        ],
    ),
    "anthropic.claude-opus-4-5-20251101-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
        ],
    ),
    "anthropic.claude-opus-4-6-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                min_input_tokens=200000,
            ),
        ],
    ),
    "anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
        ],
    ),
    "anthropic.claude-sonnet-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.0),
                output_cost_per_token=per_million_tokens(22.5),
                cache_read_cost_per_token=per_million_tokens(0.6),
                cache_creation_cost_per_token=per_million_tokens(7.5),
                min_input_tokens=200000,
            ),
        ],
    ),
    "anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.6),
                output_cost_per_token=per_million_tokens(24.75),
                cache_read_cost_per_token=per_million_tokens(0.66),
                cache_creation_cost_per_token=per_million_tokens(8.25),
                min_input_tokens=200000,
            ),
        ],
    ),
    "anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                min_input_tokens=200000,
            ),
        ],
    ),
    "anthropic.claude-v2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(8.0),
                output_cost_per_token=per_million_tokens(24.0),
            ),
        ],
    ),
    "apac.anthropic.claude-3-7-sonnet-20250219-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "apac.anthropic.claude-3-haiku-20240307-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.25),
                output_cost_per_token=per_million_tokens(1.25),
            ),
        ],
    ),
    "apac.anthropic.claude-3-sonnet-20240229-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "apac.anthropic.claude-sonnet-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.0),
                output_cost_per_token=per_million_tokens(22.5),
                cache_read_cost_per_token=per_million_tokens(0.6),
                cache_creation_cost_per_token=per_million_tokens(7.5),
                min_input_tokens=200000,
            ),
        ],
    ),
    "au.anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.1),
                output_cost_per_token=per_million_tokens(5.5),
                cache_read_cost_per_token=per_million_tokens(0.11),
                cache_creation_cost_per_token=per_million_tokens(1.375),
            ),
        ],
    ),
    "au.anthropic.claude-opus-4-6-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                min_input_tokens=200000,
            ),
        ],
    ),
    "au.anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.6),
                output_cost_per_token=per_million_tokens(24.75),
                cache_read_cost_per_token=per_million_tokens(0.66),
                cache_creation_cost_per_token=per_million_tokens(8.25),
                min_input_tokens=200000,
            ),
        ],
    ),
    "au.anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                min_input_tokens=200000,
            ),
        ],
    ),
    "eu.anthropic.claude-3-7-sonnet-20250219-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "eu.anthropic.claude-3-haiku-20240307-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.25),
                output_cost_per_token=per_million_tokens(1.25),
            ),
        ],
    ),
    "eu.anthropic.claude-3-sonnet-20240229-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "eu.anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.1),
                output_cost_per_token=per_million_tokens(5.5),
                cache_read_cost_per_token=per_million_tokens(0.11),
                cache_creation_cost_per_token=per_million_tokens(1.375),
            ),
        ],
    ),
    "eu.anthropic.claude-opus-4-5-20251101-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
        ],
    ),
    "eu.anthropic.claude-opus-4-6-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                min_input_tokens=200000,
            ),
        ],
    ),
    "eu.anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
        ],
    ),
    "eu.anthropic.claude-sonnet-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.0),
                output_cost_per_token=per_million_tokens(22.5),
                cache_read_cost_per_token=per_million_tokens(0.6),
                cache_creation_cost_per_token=per_million_tokens(7.5),
                min_input_tokens=200000,
            ),
        ],
    ),
    "eu.anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.6),
                output_cost_per_token=per_million_tokens(24.75),
                cache_read_cost_per_token=per_million_tokens(0.66),
                cache_creation_cost_per_token=per_million_tokens(8.25),
                min_input_tokens=200000,
            ),
        ],
    ),
    "eu.anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                min_input_tokens=200000,
            ),
        ],
    ),
    "global.anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.0),
                output_cost_per_token=per_million_tokens(5.0),
                cache_read_cost_per_token=per_million_tokens(0.1),
                cache_creation_cost_per_token=per_million_tokens(1.25),
            ),
        ],
    ),
    "global.anthropic.claude-opus-4-5-20251101-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.0),
                output_cost_per_token=per_million_tokens(25.0),
                cache_read_cost_per_token=per_million_tokens(0.5),
                cache_creation_cost_per_token=per_million_tokens(6.25),
            ),
        ],
    ),
    "global.anthropic.claude-opus-4-6-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.0),
                output_cost_per_token=per_million_tokens(25.0),
                cache_read_cost_per_token=per_million_tokens(0.5),
                cache_creation_cost_per_token=per_million_tokens(6.25),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(5.0),
                output_cost_per_token=per_million_tokens(25.0),
                cache_read_cost_per_token=per_million_tokens(0.5),
                cache_creation_cost_per_token=per_million_tokens(6.25),
                min_input_tokens=200000,
            ),
        ],
    ),
    "global.anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.0),
                output_cost_per_token=per_million_tokens(25.0),
                cache_read_cost_per_token=per_million_tokens(0.5),
                cache_creation_cost_per_token=per_million_tokens(6.25),
            ),
        ],
    ),
    "global.anthropic.claude-sonnet-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.0),
                output_cost_per_token=per_million_tokens(22.5),
                cache_read_cost_per_token=per_million_tokens(0.6),
                cache_creation_cost_per_token=per_million_tokens(7.5),
                min_input_tokens=200000,
            ),
        ],
    ),
    "global.anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.0),
                output_cost_per_token=per_million_tokens(22.5),
                cache_read_cost_per_token=per_million_tokens(0.6),
                cache_creation_cost_per_token=per_million_tokens(7.5),
                min_input_tokens=200000,
            ),
        ],
    ),
    "global.anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
                min_input_tokens=200000,
            ),
        ],
    ),
    "jp.anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.1),
                output_cost_per_token=per_million_tokens(5.5),
                cache_read_cost_per_token=per_million_tokens(0.11),
                cache_creation_cost_per_token=per_million_tokens(1.375),
            ),
        ],
    ),
    "jp.anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
        ],
    ),
    "jp.anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.6),
                output_cost_per_token=per_million_tokens(24.75),
                cache_read_cost_per_token=per_million_tokens(0.66),
                cache_creation_cost_per_token=per_million_tokens(8.25),
                min_input_tokens=200000,
            ),
        ],
    ),
    "jp.anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                min_input_tokens=200000,
            ),
        ],
    ),
    "us.anthropic.claude-3-5-haiku-20241022-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.8),
                output_cost_per_token=per_million_tokens(4.0),
                cache_read_cost_per_token=per_million_tokens(0.08),
                cache_creation_cost_per_token=per_million_tokens(1.0),
            ),
        ],
    ),
    "us.anthropic.claude-3-7-sonnet-20250219-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
        ],
    ),
    "us.anthropic.claude-3-haiku-20240307-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.25),
                output_cost_per_token=per_million_tokens(1.25),
            ),
        ],
    ),
    "us.anthropic.claude-3-sonnet-20240229-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "us.anthropic.claude-haiku-4-5-20251001-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.1),
                output_cost_per_token=per_million_tokens(5.5),
                cache_read_cost_per_token=per_million_tokens(0.11),
                cache_creation_cost_per_token=per_million_tokens(1.375),
            ),
        ],
    ),
    "us.anthropic.claude-opus-4-1-20250805-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(15.0),
                output_cost_per_token=per_million_tokens(75.0),
                cache_read_cost_per_token=per_million_tokens(1.5),
                cache_creation_cost_per_token=per_million_tokens(18.75),
            ),
        ],
    ),
    "us.anthropic.claude-opus-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(15.0),
                output_cost_per_token=per_million_tokens(75.0),
                cache_read_cost_per_token=per_million_tokens(1.5),
                cache_creation_cost_per_token=per_million_tokens(18.75),
            ),
        ],
    ),
    "us.anthropic.claude-opus-4-5-20251101-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
        ],
    ),
    "us.anthropic.claude-opus-4-6-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
                min_input_tokens=200000,
            ),
        ],
    ),
    "us.anthropic.claude-opus-4-7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(5.5),
                output_cost_per_token=per_million_tokens(27.5),
                cache_read_cost_per_token=per_million_tokens(0.55),
                cache_creation_cost_per_token=per_million_tokens(6.875),
            ),
        ],
    ),
    "us.anthropic.claude-sonnet-4-20250514-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
                cache_read_cost_per_token=per_million_tokens(0.3),
                cache_creation_cost_per_token=per_million_tokens(3.75),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.0),
                output_cost_per_token=per_million_tokens(22.5),
                cache_read_cost_per_token=per_million_tokens(0.6),
                cache_creation_cost_per_token=per_million_tokens(7.5),
                min_input_tokens=200000,
            ),
        ],
    ),
    "us.anthropic.claude-sonnet-4-5-20250929-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(6.6),
                output_cost_per_token=per_million_tokens(24.75),
                cache_read_cost_per_token=per_million_tokens(0.66),
                cache_creation_cost_per_token=per_million_tokens(8.25),
                min_input_tokens=200000,
            ),
        ],
    ),
    "us.anthropic.claude-sonnet-4-6": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
            ),
            PricingTier(
                input_cost_per_token=per_million_tokens(3.3),
                output_cost_per_token=per_million_tokens(16.5),
                cache_read_cost_per_token=per_million_tokens(0.33),
                cache_creation_cost_per_token=per_million_tokens(4.125),
                min_input_tokens=200000,
            ),
        ],
    ),
    # -- Cohere (via Bedrock) ------------------------------------
    "cohere.command-light-text-v14": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(0.6),
            ),
        ],
    ),
    "cohere.command-r-plus-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(3.0),
                output_cost_per_token=per_million_tokens(15.0),
            ),
        ],
    ),
    "cohere.command-r-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.5),
                output_cost_per_token=per_million_tokens(1.5),
            ),
        ],
    ),
    "cohere.command-text-v14": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.0),
                output_cost_per_token=per_million_tokens(2.0),
            ),
        ],
    ),
    "cohere.embed-english-v3": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=0.0,
            ),
        ],
    ),
    "cohere.embed-multilingual-v3": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=0.0,
            ),
        ],
    ),
    "cohere.embed-v4": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.12),
                output_cost_per_token=0.0,
            ),
        ],
    ),
    "eu.cohere.embed-v4": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.12),
                output_cost_per_token=0.0,
            ),
        ],
    ),
    "global.cohere.embed-v4": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.12),
                output_cost_per_token=0.0,
            ),
        ],
    ),
    "us.cohere.embed-v4": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.12),
                output_cost_per_token=0.0,
            ),
        ],
    ),
    # -- DeepSeek (via Bedrock) ----------------------------------
    "deepseek.r1-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.35),
                output_cost_per_token=per_million_tokens(5.4),
            ),
        ],
    ),
    "deepseek.v3.1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.58),
                output_cost_per_token=per_million_tokens(1.68),
            ),
        ],
    ),
    "deepseek.v3.2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.62),
                output_cost_per_token=per_million_tokens(1.85),
            ),
        ],
    ),
    "us.deepseek.r1-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.35),
                output_cost_per_token=per_million_tokens(5.4),
            ),
        ],
    ),
    # -- Google (via Bedrock) ------------------------------------
    "google.gemma-3-12b-it": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.09),
                output_cost_per_token=per_million_tokens(0.29),
            ),
        ],
    ),
    "google.gemma-3-27b-it": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.23),
                output_cost_per_token=per_million_tokens(0.38),
            ),
        ],
    ),
    "google.gemma-3-4b-it": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.04),
                output_cost_per_token=per_million_tokens(0.08),
            ),
        ],
    ),
    # -- Meta Llama (via Bedrock) --------------------------------
    "eu.meta.llama3-2-1b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=per_million_tokens(0.1),
            ),
        ],
    ),
    "eu.meta.llama3-2-3b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.15),
            ),
        ],
    ),
    "meta.llama2-13b-chat-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.75),
                output_cost_per_token=per_million_tokens(1.0),
            ),
        ],
    ),
    "meta.llama2-70b-chat-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.95),
                output_cost_per_token=per_million_tokens(2.56),
            ),
        ],
    ),
    "meta.llama3-1-70b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.72),
                output_cost_per_token=per_million_tokens(0.72),
            ),
        ],
    ),
    "meta.llama3-1-8b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.22),
                output_cost_per_token=per_million_tokens(0.22),
            ),
        ],
    ),
    "meta.llama3-2-11b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.16),
                output_cost_per_token=per_million_tokens(0.16),
            ),
        ],
    ),
    "meta.llama3-2-1b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=per_million_tokens(0.1),
            ),
        ],
    ),
    "meta.llama3-2-3b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.15),
            ),
        ],
    ),
    "meta.llama3-2-90b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.72),
                output_cost_per_token=per_million_tokens(0.72),
            ),
        ],
    ),
    "meta.llama3-3-70b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.72),
                output_cost_per_token=per_million_tokens(0.72),
            ),
        ],
    ),
    "meta.llama3-70b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.65),
                output_cost_per_token=per_million_tokens(3.5),
            ),
        ],
    ),
    "meta.llama3-8b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(0.6),
            ),
        ],
    ),
    "meta.llama4-maverick-17b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.24),
                output_cost_per_token=per_million_tokens(0.97),
            ),
        ],
    ),
    "meta.llama4-scout-17b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.17),
                output_cost_per_token=per_million_tokens(0.66),
            ),
        ],
    ),
    "us.meta.llama3-1-70b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.72),
                output_cost_per_token=per_million_tokens(0.72),
            ),
        ],
    ),
    "us.meta.llama3-1-8b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.22),
                output_cost_per_token=per_million_tokens(0.22),
            ),
        ],
    ),
    "us.meta.llama3-2-11b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.16),
                output_cost_per_token=per_million_tokens(0.16),
            ),
        ],
    ),
    "us.meta.llama3-2-1b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=per_million_tokens(0.1),
            ),
        ],
    ),
    "us.meta.llama3-2-3b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.15),
            ),
        ],
    ),
    "us.meta.llama3-2-90b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.72),
                output_cost_per_token=per_million_tokens(0.72),
            ),
        ],
    ),
    "us.meta.llama3-3-70b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.72),
                output_cost_per_token=per_million_tokens(0.72),
            ),
        ],
    ),
    "us.meta.llama4-maverick-17b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.24),
                output_cost_per_token=per_million_tokens(0.97),
            ),
        ],
    ),
    "us.meta.llama4-scout-17b-instruct-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.17),
                output_cost_per_token=per_million_tokens(0.66),
            ),
        ],
    ),
    # -- MiniMax (via Bedrock) -----------------------------------
    "minimax.minimax-m2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(1.2),
            ),
        ],
    ),
    "minimax.minimax-m2.1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(1.2),
            ),
        ],
    ),
    "minimax.minimax-m2.5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.3),
                output_cost_per_token=per_million_tokens(1.2),
            ),
        ],
    ),
    # -- Mistral (via Bedrock) -----------------------------------
    "mistral.devstral-2-123b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.4),
                output_cost_per_token=per_million_tokens(2.0),
            ),
        ],
    ),
    "mistral.magistral-small-2509": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.5),
                output_cost_per_token=per_million_tokens(1.5),
            ),
        ],
    ),
    "mistral.ministral-3-14b-instruct": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.2),
                output_cost_per_token=per_million_tokens(0.2),
            ),
        ],
    ),
    "mistral.ministral-3-3b-instruct": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=per_million_tokens(0.1),
            ),
        ],
    ),
    "mistral.ministral-3-8b-instruct": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.15),
            ),
        ],
    ),
    "mistral.mistral-7b-instruct-v0:2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.2),
            ),
        ],
    ),
    "mistral.mistral-large-2402-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(4.0),
                output_cost_per_token=per_million_tokens(12.0),
            ),
        ],
    ),
    "mistral.mistral-large-3-675b-instruct": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.5),
                output_cost_per_token=per_million_tokens(1.5),
            ),
        ],
    ),
    "mistral.mistral-small-2402-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.0),
                output_cost_per_token=per_million_tokens(3.0),
            ),
        ],
    ),
    "mistral.mixtral-8x7b-instruct-v0:1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.45),
                output_cost_per_token=per_million_tokens(0.7),
            ),
        ],
    ),
    "mistral.voxtral-mini-3b-2507": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.04),
                output_cost_per_token=per_million_tokens(0.04),
            ),
        ],
    ),
    "mistral.voxtral-small-24b-2507": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.1),
                output_cost_per_token=per_million_tokens(0.3),
            ),
        ],
    ),
    # -- Moonshot (via Bedrock) ----------------------------------
    "moonshotai.kimi-k2-thinking": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.6),
                output_cost_per_token=per_million_tokens(2.5),
            ),
        ],
    ),
    "moonshotai.kimi-k2.5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.6),
                output_cost_per_token=per_million_tokens(3.0),
            ),
        ],
    ),
    # -- Nvidia (via Bedrock) ------------------------------------
    "nvidia.nemotron-nano-12b-v2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.2),
                output_cost_per_token=per_million_tokens(0.6),
            ),
        ],
    ),
    "nvidia.nemotron-nano-12b-v2-vl": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.2),
                output_cost_per_token=per_million_tokens(0.6),
            ),
        ],
    ),
    "nvidia.nemotron-nano-3-30b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.06),
                output_cost_per_token=per_million_tokens(0.24),
            ),
        ],
    ),
    "nvidia.nemotron-nano-9b-v2": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.06),
                output_cost_per_token=per_million_tokens(0.23),
            ),
        ],
    ),
    "nvidia.nemotron-super-3-120b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.65),
            ),
        ],
    ),
    # -- OpenAI (via Bedrock) ------------------------------------
    "openai.gpt-oss-120b-1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.6),
            ),
        ],
    ),
    "openai.gpt-oss-20b-1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.07),
                output_cost_per_token=per_million_tokens(0.3),
            ),
        ],
    ),
    "openai.gpt-oss-safeguard-120b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.6),
            ),
        ],
    ),
    "openai.gpt-oss-safeguard-20b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.07),
                output_cost_per_token=per_million_tokens(0.2),
            ),
        ],
    ),
    # -- Qwen (via Bedrock) --------------------------------------
    "qwen.qwen3-235b-a22b-2507": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.22),
                output_cost_per_token=per_million_tokens(0.88),
            ),
        ],
    ),
    "qwen.qwen3-32b-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.6),
            ),
        ],
    ),
    "qwen.qwen3-coder-30b-a3b-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.6),
            ),
        ],
    ),
    "qwen.qwen3-coder-480b-a35b-instruct": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.45),
                output_cost_per_token=per_million_tokens(1.8),
            ),
        ],
    ),
    "qwen.qwen3-coder-next": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.5),
                output_cost_per_token=per_million_tokens(1.2),
            ),
        ],
    ),
    "qwen.qwen3-next-80b-a3b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.14),
                output_cost_per_token=per_million_tokens(1.2),
            ),
        ],
    ),
    "qwen.qwen3-vl-235b-a22b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.53),
                output_cost_per_token=per_million_tokens(2.66),
            ),
        ],
    ),
    # -- Writer (via Bedrock) ------------------------------------
    "us.writer.palmyra-x4-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.5),
                output_cost_per_token=per_million_tokens(10.0),
            ),
        ],
    ),
    "us.writer.palmyra-x5-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.6),
                output_cost_per_token=per_million_tokens(6.0),
            ),
        ],
    ),
    "writer.palmyra-vision-7b": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.15),
                output_cost_per_token=per_million_tokens(0.6),
            ),
        ],
    ),
    "writer.palmyra-x4-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(2.5),
                output_cost_per_token=per_million_tokens(10.0),
            ),
        ],
    ),
    "writer.palmyra-x5-v1": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.6),
                output_cost_per_token=per_million_tokens(6.0),
            ),
        ],
    ),
    # -- Zhipu AI (via Bedrock) ----------------------------------
    "zai.glm-4.7": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.6),
                output_cost_per_token=per_million_tokens(2.2),
            ),
        ],
    ),
    "zai.glm-4.7-flash": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(0.07),
                output_cost_per_token=per_million_tokens(0.4),
            ),
        ],
    ),
    "zai.glm5": ModelPricing(
        tiers=[
            PricingTier(
                input_cost_per_token=per_million_tokens(1.0),
                output_cost_per_token=per_million_tokens(3.2),
            ),
        ],
    ),
}

_REGIONAL_PRICING: dict[str, dict[str, ModelPricing]] = {}

# Pre-sorted by key length descending for longest-prefix matching
_PRICING_BY_PREFIX = sorted(_PRICING.items(), key=lambda item: len(item[0]), reverse=True)


def calculate_bedrock_cost(model: str, usage: Usage, *, region: str | None = None) -> Cost | None:
    """Calculate cost for a Bedrock API call. Returns None if model pricing is unknown."""
    # Try regional pricing first if region specified
    if region is not None and region != "us-east-1":
        regional = _REGIONAL_PRICING.get(region, {})
        pricing = regional.get(model)
        if pricing is None:
            for prefix, p in sorted(regional.items(), key=lambda item: len(item[0]), reverse=True):
                if model.startswith(prefix):
                    pricing = p
                    break
        if pricing is not None:
            return calculate_cost(usage, pricing)

    # Fall back to default (us-east-1) pricing
    pricing = _PRICING.get(model)
    if pricing is None:
        for prefix, p in _PRICING_BY_PREFIX:
            if model.startswith(prefix):
                pricing = p
                break
    if pricing is None:
        return None
    return calculate_cost(usage, pricing)
